name: parcial_2
description: "Parcial Flutter — Accidentes Tuluá + CRUD Establecimientos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP client
  dio: ^5.8.0+1

  # Navegación declarativa
  go_router: ^15.1.3

  # Variables de entorno
  flutter_dotenv: ^5.2.1

  # Gráficas
  fl_chart: ^1.0.0

  # Skeleton loading
  skeletonizer: ^2.1.3

  # Selector de imágenes
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
